name: (Docker) Build and Push

on:
  workflow_call:
    inputs:
      semantic_version:
        description: 'Version number of the docker image'
        default: latest
        type: string
      registry_url:
        description: 'URL of the registry'
        default: registry.nomadevops.co
        type: string

    secrets:
      registry_user:
      registry_pwd:

jobs:
  build_and_push:
    runs-on: arc-runner-set
    steps:
      - name: Download Docker Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-artifact

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry_url }}
          username: ${{ secrets.registry_user }}
          password: ${{ secrets.registry_pwd }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ inputs.registry_url }}/${{ github.event.repository.name }}:${{ inputs.semantic_version }}
