name: MicroK8S deployment

on:
  workflow_call:
    inputs:
      kubernetes_namespace:
        description: 'Namespace to deploy'
        default: tools
        type: string
      helm_release:
        description: 'Name of the release'
        required: true
        type: string
      has_dependency:
        description: 'Flag to set if your chart has dependency'
        required: false
        default: false
        type: boolean
    secrets:
      MICROK8S_CONFIG:
      additional_set:

jobs:
  Install-Helm:
    name: Install Helm
    runs-on: arc-runner-set
    steps:
      - name: Install Helm
        run: |
          sudo apt update -y && sudo apt install -y curl
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        shell: bash

      - name: Find Helm Binary & Package It
        run: |
          HELM_BINARY=$(which helm)
          cp $HELM_BINARY ./helm
          chmod +x ./helm
        shell: bash

      - name: Upload Helm Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-binary
          path: ./helm

  Lint:
    name: Linter
    runs-on: arc-runner-set
    needs: Install-Helm
    steps:
      - uses: actions/checkout@v4

      - name: Download Helm Binary
        uses: actions/download-artifact@v4
        with:
          name: helm-binary

      - name: Make Helm Executable
        run: chmod +x ./helm
        shell: bash
      
      - name: Running Linter
        run: ./helm lint .
        shell: bash

  Deployment:
    name: Deploy on MicroK8S Cluster
    runs-on: arc-runner-set
    needs: [Install-Helm, Lint]
    steps:
      - uses: actions/checkout@v4

      - name: Download Helm Binary
        uses: actions/download-artifact@v4
        with:
          name: helm-binary

      - name: Make Helm Executable
        run: chmod +x ./helm
        shell: bash

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.MICROK8S_CONFIG }}
      
      - name: Helm Dependency Update
        if: ${{ inputs.has_dependency }}
        run: ./helm dependency update
        shell: bash

      - name: Install Chart 
        run: |
          if [ -n "${{ secrets.additional_set }}" ]; then
            ./helm upgrade --install ${{ inputs.helm_release }} -n ${{ inputs.kubernetes_namespace }} --set ${{ secrets.additional_set }} --create-namespace .
          else
            ./helm upgrade --install ${{ inputs.helm_release }} -n ${{ inputs.kubernetes_namespace }} --create-namespace .
          fi  
        shell: bash