name: Deploy on MicroK8S using Helm

on:
  workflow_call:
    inputs:
      kubernetes_namespace:
        description: 'Namespace to deploy'
        default: tools
        type: string
      helm_release:
        description: 'Name of the release'
        required: true
        type: string
    secrets:
      MICROK8S_CONFIG:

jobs:
  Lint:
      name: Linter
      runs-on: arc-runner-set
      steps:
        - uses: actions/checkout@v4
        - name: Install helm binary
          run: |
              sudo apt update -y && sudo apt install -y curl
              curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          shell: bash
        - name: Running Linter
          run: helm lint
          shell: bash
    
  Deployment:
    name: Deploy on microk8s cluster
    runs-on: arc-runner-set
    needs: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Install helm binary
        run: |
            sudo apt update -y && sudo apt install -y curl
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        shell: bash
      
      - name: Connect to cluster
        uses: azure/k8s-set-context@v4
        with:
           method: kubeconfig
           kubeconfig: ${{secrets.MICROK8S_CONFIG}}
      
      - name: Install Chart
        run: |
          helm upgrade --install ${{ inputs.helm_release }} -n ${{ inputs.kubernetes_namespace }} --create-namespace .
